/* root */
export const SHOW_PAGE_LOADING = 'SHOW_PAGE_LOADING';
export const HIDE_PAGE_LOADING = 'HIDE_PAGE_LOADING';
export const PROVINCE = 'PROVINCE';
export const PERMISSIONS = 'PERMISSIONS';
export const USER_ROLE_LIST = 'USER_ROLE_LIST';
export const ROUTE_CHANGE = 'ROUTE_CHANGE';
export const CURRENT_USER_GET_INFO = 'CURRENT_USER_GET_INFO';
export const ADD_ROUTES = 'ADD_ROUTES';
export const STATIC_DATA = 'STATIC_DATA';
export const FIRST_PAGE = 'FIRST_PAGE';

/* login */
export const SET_LOGIN_USER = 'SET_LOGIN_USER';
export const LOG_OUT = 'LOG_OUT';

/* system */
export const ROLE_LIST = 'ROLE_LIST';
export const ROLE_INIT_FORM = 'ROLE_INIT_FORM';
export const ROLE_GET_INFO = 'ROLE_GET_INFO';
export const USER_GET_LIST = 'USER_GET_LIST';
export const USER_INIT_FORM = 'USER_INIT_FORM';
export const USER_GET_INFO = 'USER_GET_INFO';
export const SYSTEM_QUERY_REGION = 'SYSTEM_QUERY_REGION';
export const ROLE_REDIRECT_USER_CREATE = 'ROLE_REDIRECT_USER_CREATE';
export const SYS_CONFIG = 'SYS_CONFIG';

/* data-analysis */
export const CLIENT_GET = 'CLIENT_GET';
export const ACTIVE_GET_DAILY_USER = 'ACTIVE_GET_DAILY_USER';
export const ACTIVE_GET_MEMBERS = 'ACTIVE_GET_MEMBERS';
export const TREND_GET_LIST = 'TREND_GET_LIST';
export const TREND_GET_NEW_MEMBERS = 'TREND_GET_NEW_MEMBERS';
export const ACTIVE_UPDATE_TREND = 'ACTIVE_UPDATE_TREND';
export const PROVINCE_GET_MAP_JSON = 'PROVINCE_GET_MAP_JSON';
export const PROVINCE_GET_USER = 'PROVINCE_GET_USER';
export const RETENTION_GET_USER = 'RETENTION_GET_USER';
export const RETENTION_GET_TREND_LIST = 'RETENTION_GET_TREND_LIST';
export const RETENTION_UPDATE_PROVINCE_TREND_LIST = 'RETENTION_UPDATE_PROVINCE_TREND_LIST';
export const ACTIVE_INIT_DATE = 'ACTIVE_INIT_DATE';
export const PROVINCER_USER_INIT_DATE = 'PROVINCER_USER_INIT_DATE';

export const ADD_USER_OVERVIEW = 'ADD_USER_OVERVIEW';
export const ADD_USER_MAP = 'ADD_USER_MAP';
export const ADD_USER_TREND = 'ADD_USER_TREND';
export const ADD_USER_VIP = 'ADD_USER_VIP';
export const INIT_ADD_USER_VIP_TYPE = 'INIT_ADD_USER_VIP_TYPE';

export const ADD_USER_DISTRICT_MAP = 'ADD_USER_DISTRICT_MAP';

export const ADD_USER_PROVINCE_TREND = 'ADD_USER_PROVINCE_TREND';

export const ADD_USER_VIP_CHART = 'ADD_USER_VIP_CHART';
export const ADD_USER_LAST_MONTH_VIP = 'ADD_USER_LAST_MONTH_VIP';

/* task */
export const TASK_QUERY_LIST = 'TASK_QUERY_LIST';
export const TASK_GET_DETAIL = 'TASK_GET_DETAIL';
export const SET_PUSH_LIST = 'SET_PUSH_LIST';
export const SET_TODO_LIST = 'SET_TODO_LIST';

/* order */
export const ORDER_GET_LIST = 'ORDER_GET_LIST';
export const ORDER_OV_SIGN_HANDLE = 'ORDER_OV_SIGN_HANDLE';
export const ORDER_CREATE = 'ORDER_CREATE';
export const ORDER_QUERY_ORGANIZE_ADDRESS = 'ORDER_QUERY_ORGANIZE_ADDRESS';
export const ORDER_GET_DETAIL = 'ORDER_GET_DETAIL';
export const ORDER_CM_GET_LIST = 'ORDER_CM_GET_LIST';
export const ORDER_HT_GET_LIST = 'ORDER_HT_GET_LIST';
export const ORDER_QUERY_ASSIGN_HANDLER = 'ORDER_QUERY_ASSIGN_HANDLER';
export const ORDER_QUERY_PRODUCT_HANDLER = 'ORDER_QUERY_PRODUCT_HANDLER';
export const ORDER_GET_HANDLE_TASK_DETAIL = 'ORDER_GET_HANDLE_TASK_DETAIL';
export const ORDER_SUBMIT_ORDER_ROW = 'ORDER_SUBMIT_ORDER_ROW';
export const ORDER_DELETE_ORDER_ROW = 'ORDER_DELETE_ORDER_ROW';
export const ORDER_UPDATE_PROCESS_ID = 'ORDER_UPDATE_PROCESS_ID';
export const ORDER_OVERVIEW_GET_DETAIL = 'ORDER_OVERVIEW_GET_DETAIL';
export const ORDER_GET_PROCESS_LIST = 'ORDER_GET_PROCESS_LIST';
export const ORDER_UPDATE_CREATE = 'ORDER_UPDATE_CREATE';
export const ORDER_GET_EDIT = 'ORDER_GET_EDIT';
export const ORDER_QUERY_PRODUCT_NAME = 'ORDER_QUERY_PRODUCT_NAME';
export const ORDER_SUBMIT_ASSIGN_BUTTON_STATUS = 'ORDER_SUBMIT_ASSIGN_BUTTON_STATUS';
export const ORDER_GET_HAS_SIGNED_FILE = 'ORDER_GET_HAS_SIGNED_FILE';
export const ORDER_OVERVIEW_PAGE_CHANGE = 'ORDER_OVERVIEW_PAGE_CHANGE';
export const ORDER_CM_PAGE_CHANGE = 'ORDER_CM_PAGE_CHANGE';
export const ORDER_HT_PAGE_CHANGE = 'ORDER_HT_PAGE_CHANGE';
export const ORDER_LAST_PROCESS_INFO = 'ORDER_LAST_PROCESS_INFO';
export const ORDER_REMOVE_PROCESS_LIST = 'ORDER_REMOVE_PROCESS_LIST';
export const ORDER_DELETE_PRODUCT = 'ORDER_DELETE_PRODUCT';
export const ORDER_HANDLE_PROCESS = 'ORDER_HANDLE_PROCESS';
export const ORDER_GET_HAS_SIGNED_FILE_LIST = 'ORDER_GET_HAS_SIGNED_FILE_LIST';
export const ORDER_ADD_PRODUCT = 'ORDER_ADD_PRODUCT';
export const ORDER_REMOVE_PAY_DETAIL_FILES = 'ORDER_REMOVE_PAY_DETAIL_FILES';
export const ORDER_INIT_CREATE = 'ORDER_INIT_CREATE';
export const ORDER_EDIT_PROCESSOR_TO_NAME = 'ORDER_EDIT_PROCESSOR_TO_NAME';

/* group_customer */
export const GROUP_CUSTOMER_INIT_FORM = 'GROUP_CUSTOMER_INIT_FORM';
export const GROUP_CUSTOMER_GET_LIST = 'GROUP_CUSTOMER_GET_LIST';
export const GROUP_CUSTOMER_GET_INFO = 'GROUP_CUSTOMER_GET_INFO';
export const GROUP_CUSTOMER_MANAGERS = 'GROUP_CUSTOMER_MANAGERS';
export const GROUP_CUSTOMER_DETAIL = 'GROUP_CUSTOMER_DETAIL';
export const GROUP_CUSTOMER_SUBSCRIBE_PRODUCTS = 'GROUP_CUSTOMER_SUBSCRIBE_PRODUCTS';
export const GROUP_CUSTOMER_PROCESSES = 'GROUP_CUSTOMER_PROCESSES';
export const TAG_LIBRARY_LIST = 'TAG_LIBRARY_LIST';
export const GROUP_NAME_LIST = 'GROUP_NAME_LIST';
export const GROUP_VENDOR_NAME_LIST = 'GROUP_VENDOR_NAME_LIST';

/* product */
export const PRODUCT_LIST = 'PRODUCT_LIST';
export const PRODUCT_CREAT_LIST = 'PRODUCT_CREAT_LIST';
export const PRODUCT_DETAIL = 'PRODUCT_DETAIL';
export const COMPOSED_PRODUCT = 'COMPOSED_PRODUCT';
export const DETAIL_SALE = 'DETAIL_SALE';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const SAVE_BASE_INFO = 'SAVE_BASE_INFO';
export const SAVE_SALE_STEP = 'SAVE_SALE_STEP';
export const PRODUCT_LIBRARY_LIST = 'PRODUCT_LIBRARY_LIST';
export const PRODUCT_OUTOF_LIBRARY_LIST = 'PRODUCT_OUTOF_LIBRARY_LIST';
export const PRODUCT_TASK_INFO_LIST = 'PRODUCT_TASK_INFO_LIST';
export const OWNERSHIP_COMPANY_LIST = 'OWNERSHIP_COMPANY_LIST';
export const SALES_CASE_DETAIL = 'SALES_CASE_DETAIL';
export const ADD_SALES_PRODUCTS = 'ADD_SALES_PRODUCTS';
export const UNDER_CARRIAGE_PRODUCT = 'UNDER_CARRIAGE_PRODUCT';
export const ADD_SALES_CASE = 'ADD_SALES_CASE';
export const EDIT_SALES_CASE = 'EDIT_SALES_CASE';
export const DEL_SALES_CASE = 'DEL_SALES_CASE';
export const BROKER_LIST = 'BROKER_LIST';
export const FIRST_COLLECTION_LIST = 'FIRST_COLLECTION_LIST';
export const CORE_ABILITY_LIST = 'CORE_ABILITY_LIST';
export const FIRST_COLLECTION_TYPE = 'FIRST_COLLECTION_TYPE';
export const CORE_ABILITY_TYPE = 'CORE_ABILITY_TYPE';
export const PRODUCT_CASE_DETAIL = 'PRODUCT_CASE_DETAIL';
export const PRODUCT_NAME_LIST = 'PRODUCT_NAME_LIST';
export const SPEC_PRODUCT_LIST = 'SPEC_PRODUCT_LIST';
/* business */
export const COOPERATION_GROUP = 'COOPERATION_GROUP';
export const BUSINESS_OPPORTUNITY_LIST = 'BUSINESS_OPPORTUNITY_LIST';
export const BUSINESS_DETAIL = 'BUSINESS_DETAIL';
export const OFFICE_ADDRESS = 'OFFICE_ADDRESS';
export const SUBMIT_BUSINESS_STATUS = 'SUBMIT_BUSINESS_STATUS';
export const GROUP_ASSOCIATION_STATUS = 'GROUP_ASSOCIATION_STATUS';
export const DEL_BUSINESS_STATUS = 'DEL_BUSINESS_STATUS';
export const DESIGNATE_PERSON = 'DESIGNATE_PERSON';
export const REMIND_PERSON = 'REMIND_PERSON';
export const SUBMIT_BUSINESS_SEND_STATUS = 'SUBMIT_BUSINESS_SEND_STATUS';
export const SUBMIT_BUSINESS_CANCEL_STATUS = 'SUBMIT_BUSINESS_CANCEL_STATUS';
export const SAVE_BUSINESS_DRAFT_STATUS = 'SAVE_BUSINESS_DRAFT_STATUS';
export const SAVE_BUSINESS_ORDER = 'SAVE_BUSINESS_ORDER';
export const SAVE_BUSINESS_ORDER_DRAFT = 'SAVE_BUSINESS_ORDER_DRAFT';
export const MY_BUSINESS_LIST = 'MY_BUSINESS_LIST';
export const BUSINESS_TASK_LIST = 'BUSINESS_TASK_LIST';
export const TRANSFOR_ORDER_DETAIL = 'TRANSFOR_ORDER_DETAIL';
export const SUBMIT_BUSINESS_DRAFT_STATUS = 'SUBMIT_BUSINESS_DRAFT_STATUS';
export const EDIT_BUSINESS_DETAIL_STATUS = 'EDIT_BUSINESS_DETAIL_STATUS';
export const PRODUCT_NAME_CODE = 'PRODUCT_NAME_CODE';
export const EDIT_BUSINESS_DETAIL_APPROVE_STATUS = 'EDIT_BUSINESS_DETAIL_APPROVE_STATUS';
export const QUERY_TASK = 'QUERY_TASK';
export const PRODUCT_DTO_LIST = 'PRODUCT_DTO_LIST';
export const PRODUCT_DTO_CREATE = 'PRODUCT_DTO_CREATE';
export const PRODUCT_DTO_DELETE = 'PRODUCT_DTO_DELETE';
export const QUERY_PRODUCT_PROCESSOR = 'QUERY_PRODUCT_PROCESSOR';
export const GET_PRODUCT_PROCESSOR = 'GET_PRODUCT_PROCESSOR';
export const PRODUCT_DTO_INPUT_CLEAR = 'PRODUCT_DTO_INPUT_CLEAR';
export const CLEAR_BUSINESS_PRODUCT = 'CLEAR_BUSINESS_PRODUCT';
/* requirement */
export const REQUIREMENT_GET_LIST = 'REQUIREMENT_GET_LIST';
export const REQUIREMENT_GET_INFO = 'REQUIREMENT_GET_INFO';
export const REQUIREMENT_TASK_LIST = 'REQUIREMENT_TASK_LIST';
export const REQUIREMENT_PROCESSORS = 'REQUIREMENT_PROCESSORS';
export const REQUIREMENT_CREATE_PROCESSORS = 'REQUIREMENT_CREATE_PROCESSORS';

/* visit */
export const MY_VISIT_MANAGE_LIST = 'MY_VISIT_MANAGE_LIST';
export const CREATE_VISIT_DATA = 'CREATE_VISIT_DATA';
export const APPOINT_VISIT_LIST = 'APPOINT_VISIT_LIST';
export const VISIT_APPOINT_DETAIL = 'VISIT_APPOINT_DETAIL';
export const REGION_MANAGE_LIST = 'REGION_MANAGE_LIST';
export const GET_PROCESSOR_LIST = 'GET_PROCESSOR_LIST';
export const HANDLE_VISIT_MANAGE_LIST = 'HANDLE_VISIT_MANAGE_LIST';
export const REGISTER_LIST = 'REGISTER_LIST';
export const VISIT_DETAIL = 'VISIT_DETAIL';
export const VISIT_ASSIGN_DETAIL = 'VISIT_ASSIGN_DETAIL';
export const APPOINT_CREATE = 'APPOINT_CREATE';
export const APPLICATION_CREATE = 'APPLICATION_CREATE';

/* dashboard */
export const HOME_MODULE = 'HOME_MODULE';
export const HOME_MODULE_FROM_MENU = 'HOME_MODULE_FROM_MENU';
export const UPDATE_HOME_MODULE_STATUS = 'UPDATE_HOME_MODULE_STATUS';
export const HOME_BUSINESS_LIST = 'HOME_BUSINESS_LIST';
export const HOME_ORDER_LIST = 'HOME_ORDER_LIST';
export const HOME_QUERY_TASK_INFO_ORANGIZE = 'HOME_QUERY_TASK_INFO_ORANGIZE';
export const HOME_QUERY_TASK_INFO_ORDER = 'HOME_QUERY_TASK_INFO_ORDER';
export const HOME_QUERY_TASK_INFO_BUSINESS = 'HOME_QUERY_TASK_INFO_BUSINESS';
export const HOME_QUERY_TASK_INFO_REQUIRE = 'HOME_QUERY_TASK_INFO_REQUIRE';
export const HOME_QUERY_TASK_INFO_VISIT = 'HOME_QUERY_TASK_INFO_VISIT';
export const HOME_QUERY_ORGANIZE_INFO = 'HOME_QUERY_ORGANIZE_INFO';
export const HOME_QUERY_TRAIN_INFO = 'HOME_QUERY_TRAIN_INFO';

/* data-extraction */
export const DATA_EXTRACTION_DOWMLOAD = 'DATA_EXTRACTION_DOWMLOAD';
export const DATA_EXTRACTION_STEPS = 'DATA_EXTRACTION_STEPS';
export const DATA_EXTRACTION_DETAIL_DATA = 'DATA_EXTRACTION_DETAIL_DATA';
export const DATA_EXTRACTION_AUDIT = 'DATA_EXTRACTION_AUDIT';
export const DATA_EXTRACTION_TASK = 'DATA_EXTRACTION_TASK';
export const PROCESSOR_LIST = 'ROCESSOR_LIST';

/* train */
export const TRAIN_CM_PAGE_CHANGE = 'TRAIN_CM_PAGE_CHANGE';
export const TRAIN_GET_CREATE_MANAGE = 'TRAIN_GET_CREATE_MANAGE';
export const TRAIN_CREATE_ADD_LINE = 'TRAIN_CREATE_ADD_LINE';
export const TRAIN_ADD_TIME_OBJ = 'TRAIN_ADD_TIME_OBJ';
export const TRAIN_CREATE_ADD_ITEM = 'TRAIN_CREATE_ADD_ITEM';
export const TRAIN_CREATE_REDUCE_ITEM = 'TRAIN_CREATE_REDUCE_ITEM';
export const TRAIN_CREATE_UPDATE_ITEM = 'TRAIN_CREATE_UPDATE_ITEM';
export const TRAIN_GET_CREATE_MANAGEMENT_LIST = 'TRAIN_GET_CREATE_MANAGEMENT_LIST';
export const TRAIN_IMPORT_EXCEL = 'TRAIN_IMPORT_EXCEL';
export const TRAIN_GET_DETAIL = 'TRAIN_GET_DETAIL';
export const TRAIN_CLEAR_CREATE = 'TRAIN_CLEAR_CREATE';
export const TRAIN_GET_EDIT = 'TRAIN_GET_EDIT';
export const TRAIN_GET_APPLY_CENTER = 'TRAIN_GET_APPLY_CENTER';
export const TRAIN_APPLYC_PAGE_CHANGE = 'TRAIN_APPLYC_PAGE_CHANGE';
export const TRAIN_MY_PAGE_CHANGE = 'TRAIN_MY_PAGE_CHANGE';
export const TRAIN_GET_MY = 'TRAIN_GET_MY';
export const TRAIN_CREATE_IS_DATE_CHANGE = 'TRAIN_CREATE_IS_DATE_CHANGE';
export const TRAIN_CREATE_ORIGIN_DATE = 'TRAIN_CREATE_ORIGIN_DATE';
export const TRAIN_CREATE_MINUS_LINE = 'TRAIN_CREATE_MINUS_LINE';
export const TRAIN_CHANGE_FILE_FLAG = 'TRAIN_CHANGE_FILE_FLAG';
export const TRAIN_CLEAR_REFS_ITEM_OBJ = 'TRAIN_CLEAR_REFS_ITEM_OBJ';
export const TRAIN_TIME_TRANSFOR = 'TRAIN_TIME_TRANSFOR';
export const TRAIN_FILE_NAME_CHANGE = 'TRAIN_FILE_NAME_CHANGE';
export const TRAIN_CHANGE_COURSE_FILE_NAME = 'TRAIN_CHANGE_COURSE_FILE_NAME';
export const TRAIN_DESTORY_DETAIL = 'TRAIN_DESTORY_DETAIL';

/* activity */
export const ACTIVITY_LIST = 'ACTIVITY_LIST';
export const MARKET_ACTIVITY_PAGE_CHANGE = 'MARKET_ACTIVITY_PAGE_CHANGE';
export const MARKET_ACTIVITY_TASK_PAGE_CHANGE = 'MARKET_ACTIVITY_TASK_PAGE_CHANGE';
export const MARKET_ACTIVITY_GEY_DETAIL = 'MARKET_ACTIVITY_GEY_DETAIL';
export const ACTIVITY_DETAIL = 'ACTIVITY_DETAIL';
export const ACTIVITY_RATE_LIST = 'ACTIVITY_RATE_LIST';
export const ACTIVITY_SELECT_REGION_TREE = 'ACTIVITY_SELECT_REGION_TREE';
export const CREATE_ACTIVITY_FORM = 'CREATE_ACTIVITY_FORM';
export const SUBMIT_RATE_ACTIVITY_FORM = 'SUBMIT_RATE_ACTIVITY_FORM';
export const CREATE_ACTIVITY_VALUE_UPDATE = 'CREATE_ACTIVITY_VALUE_UPDATE';